name: continuous integration # Continue Integration

# When pushed to the branch, trigger the workflow
on:
  push:
    branches: [main] # "**" <- any branch

# When the event occurs (pushed to main branch), run these jobs
jobs:
  test_codebase: # name of the job
    runs-on: ubuntu-latest # run on this computer (latest version of ubuntu)
    steps:
      - uses: actions/checkout@v2 # an existing action defined by github
      - name: test codebase # name of the job
        run: pytest # command to run
